### ISSUE TITLE
Commerce Tail Logs

### ISSUE THREAD

**Issue by rwalter215** [adobe/aio-lib-cloudmanager#206]
**Is your feature request related to a problem? Please describe.**
Commerce customers need to be able to retrieve tail logs for the various commands they run.

**Describe the solution you'd like**
We need to implement a function that calls the tail log endpoint and returns the output.

**Describe alternatives you've considered**

**Additional context**

**Comment by justinedelson** [comment]
@rwalter215 looking at @thoughtassassin 's PR: https://github.com/adobe/aio-cli-plugin-cloudmanager/pull/448

it seems like this new method will be named `getCommerceTailLogs`. I think it would be a bit more consistent to name this `tailCommerceCommandExecutionLog`

Then we would have:

* `tailLog` (should probably be deprecated and replaced with `tailEnvironmentLog`)
* `tailExecutionStepLog`
* `tailCommerceCommandExecutionLog`

WDYT?
